# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='muzikland',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='song',
            name='muzikland',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='style',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Muzikland',
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(to='music.Singer'),
        ),
    ]
