# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170525_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='cover',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
