# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170605_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music',
            field=models.FileField(null=True, upload_to='music'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
